#!/bin/bash
#
# Launcher for the LEAP Client under OSX
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
export DYLD_LIBRARY_PATH=$DIR
export PATH=$DIR/../Resources/:$PATH
# ---------------------------
# DEBUG Info -- enable this if you
# are having problems with dynamic libraries loading

#export DYLD_PRINT_LIBRARIES=1
# ---------------------------
# XXX FIXME !!!!!!!!!!!!!!!!!!
# REMOVE NOCHECK FLAG FOR PRODUCTION USE !!!!!!!!
#
cd "${DIR}" && ./launcher --danger $1 $2 $3 $4 $5
